# Generated by Django 5.0.4 on 2024-04-26 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_phone_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
